[package]
name = "tuna-man"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0-or-later"

[dependencies]
clap = { version = "4.5.20", features = ["derive"] }
csv = "1.3.0"
fastrand = "2.1.1"
serde = { version = "1.0.210", default-features = false, features = ["derive"] }
