[package]
name = "pingpong"
version = "0.1.0"
edition = "2021"

[dependencies]
csv = "1.3.0"
fastrand = "2.1.1"
ratatui = "0.28.1"
serde = { version = "1.0.210", default-features = false, features = ["derive"] }
