name: Rust

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: macos-latest
            target: aarch64-apple-darwin
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          - os: windows-latest
            target: x86_64-pc-windows-msvc



    steps:
    - uses: actions/checkout@v4
    - uses: swatinem/rust-cache@v2
    
    - name: Build in release mode
      run: cargo build --release --target ${{ matrix.target }} --verbose
    - name: Run tests
      run: cargo test --target ${{ matrix.target }} --verbose
